language: node_js
node_js:
  - 14.3

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node

after_success:
  - echo "finished building"
